#Promise
所谓Promise,简单说就是一个容器,里面保存了某个未来才会结束的事件(通常是一个异步操作)的结果.
Promise对象有两个特点:  
(1) 对象的状态不受外界影响. 只有异步操作的结果可以决定状态    
(2) 一旦状态改变,就不会再变,任何时候都可以得到这个结果
###用法
	var promise = new Promise(function(resolve, reject) {
	  	// ... some code
	  	if (/* 异步操作成功 */){
	    	resolve(value);
	  	} else {
	    	reject(error);
	  	}
	});
	// resolve函数的作用是,将Promise对象的状态从'未完成'变成'成功'(从pending变为resolved),并将异步操作的结果作为参数传递出去
	// reject函数的作用是,是将promise对象的状态从'未完成'变为 '失败',并将错误当做参数传递出去
	
promise实例生成以后,可以用then方法分别指定resolved状态和rejected状态的回调函数,其中rejected函数可选.这两个函数都接受promise对象传出的值作为参数.
	
	function timeout(ms) {
  		return new Promise((resolve, reject) => {
    		setTimeout(resolve, ms, 'done');    // 这里 'done'是resolve函数第一个参数
  		});
	}
	timeout(100).then((value) => {
  		console.log(value);    // 输出'done'
	});    

###用promise对象封装ajax
	
	const getJson =  (url) => {
		return promise = new Promise((resolve,reject) => {
			const handler = () => {
				if(this.readyState !== 4) return
				if(this.status === 200){
					resolve(this.response);  // 处理成功请求,传递数据出去
				}else {
					reject(this.statusText);  // 处理失败请求,传递错误信息出去
				}
			}
			const ajax = new XMLHttpRequest();
			ajax.open('GET',url);
			ajax.onreadystatechange = handler;
			ajax.responseType = 'json';
			ajax.setRequestHeader('Accept','application/json');
			ajax.send()
		});
	}

###Promisez作为resolve函数参数
	const p1 = new Promise(function (resolve, reject) {
  		setTimeout(() => reject(new Error('fail')), 3000)
	})

	const p2 = new Promise(function (resolve, reject) {
  		setTimeout(() => resolve(p1), 1000)
	})

	p2.then(result => console.log(result))
	.catch(error => console.log(error))  
	// 此处p1的状态传递给p2,p1的状态决定了p2的状态,如果p1的状态已经是resolved或者rejected,p2的回调才会执行
###调用resolve不会终结Promiss
	new Promise((resolve, reject) => {
  		resolve(1);
  		console.log(2);
	}).then(r => {
  		console.log(r);
	});
	// 2
	// 1

上面代码里,会先打印2,因为resolve在本轮事件循环的末尾执行. 
###then,catch方法
then方法是定义在原型对象Promise.protoType上面的,作用是为Promise实例添加状态改变时的回调函数.then函数有两个参数: resovlved和rejected回调   
then方法返回一个**新的**Promise实例,可以链式编程.   
catch方法也是定义在原型对象Promise.protoType上面. 是.then(null,rejection)的别名,用于指定发生错误时的回调函数. 
	
	p.then((val) => console.log('fulfilled:', val))
  	.catch((err) => console.log('rejected', err));

	// 等同于
	p.then((val) => console.log('fulfilled:', val))
  	.then(null, (err) => console.log("rejected:", err));  

Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获,跟传统的try/catch代码块不同的是，如果没有使用catch方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。浏览器运行到这一行，会打印出错误提示ReferenceError: x is not defined，但是不会退出进程、终止脚本执行

###Promise.all()
用于将多个Promise实例,包装成一个新的Promise实例  
接受一个数组(可以不是数组,但是必须要有Iterator接口)作为参数,每个成员都是Promise实例,如果不是,会默认调用Promise.sesolve方法转为Promise实例    
	
	const p = Promise.all([p1, p2, p3]);
	
	p的状态由p1、p2、p3决定，分成两种情况 :
	(1):只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled，此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数。
	(2):只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected，此时第一个被reject的实例的返回值，会传递给p的回调函数

###Promise.race()
Promise.race方法同样将多个Promise实例,包装成一个新的Promise
	
	const p = Promise.race([p1, p2, p3]);
	// 上述代码中,只要p1,p2,p3之中有一个实例率先改变状态,P的状态就跟着改变,那个率先改变的Promise实例的返回值,就传给p的回调函数,参数规则同promise.all()
	
###Promise.resolve()
有时需要将现有的对象转为Promise对象,Promise.resolve方法就起这个作用  
Promise.resolve方法的参数分成四种情况:   
(1) 参数是一个Promise实例,不做修改,原样返回
(2) 参数是一个thenable对象(具有then方法的对象),Promise.resolve方法会将这个对象转为Promise对象,状态是resolved,然后立即执行then方法
(3) 参数是原始值,返回一个新的Promise对象,状态是resolved
(4) 不带有任何参数,直接返回一个resolved状态的Promise对象

	setTimeout(function () {
	  console.log('three');
	}, 0);

	Promise.resolve().then(function () {
	  console.log('two');
	});

	console.log('one');
	// 立即resolved的Promise对象,是在本轮'事件循环'(event loop)的结束时,而不是在下一轮'事件循环的'开始
###Promise.reject()
Promise.reject方法返回一个新的Promise实例,该实例的状态是rejected



